name: minecraft-bedrock-server

on:
  push:

jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      tags: |
        waterlemons2k/minecraft-bedrock-server
        waterlemons2k/minecraft-bedrock-server:1.19.51.01
    secrets:
      TOKEN: ${{ secrets.TOKEN }}