name: minecraft-bedrock-server

on:
  push:

env:
  name: minecraft-bedrock-server #镜像名称
  tag: "1.19.51.01" #第二镜像标签

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: waterlemons2k
          password: ${{ secrets.TOKEN }}

      - name: Build and push
        run: |
          docker build -t waterlemons2k/${{ env.name }}:latest -t waterlemons2k/${{ env.name }}:${{ env.tag }} .
          docker push -a waterlemons2k/${{ env.name }}
